version: "3"

services:
  mail-manager-gateway:
    image: mail-manager-gateway:0.0.1
    container_name: manager-gateway
    ports:
      -
    volumes:
      - /mail_cloud/data/manager-gateway:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos

  mail-user-gateway:
    image: mail-user-gateway:0.0.1
    container_name: user-gateway
    ports:
      -
    volumes:
      - /mail_cloud/data/user-gateway:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos

  mail-cart-service:
    image: mail-cart-service:0.0.1
    container_name: cart-service
    ports:
      -
    volumes:
      - /mail_cloud/data/cart-service:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos
      - mail-rabbitmq

  mail-goods-service:
    image: mail-goods-service:0.0.1
    container_name: goods-service
    ports:
      -
    volumes:
      - /mail_cloud/data/goods-service:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos

  mail-manager-service:
    image: mail-manager-service:0.0.1
    container_name: manager-service
    ports:
      -
    volumes:
      - /mail_cloud/data/manager-service:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos

  mail-order-service:
    image: mail-order-service:0.0.1
    container_name: order-service
    ports:
      -
    volumes:
      - /mail_cloud/data/order-service:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos
      - mail-rabbitmq
  mail-user-service:
    image: mail-user-service:0.0.1
    container_name: user-service
    ports:
      -
    volumes:
      - /mail_cloud/data/user-service:/data
    networks:
      - mail_cloud_net
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mail-mysql
      - mail-redis
      - mail-nacos

  mail-nacos:
    image: nacos/nacos-server:1.4.1
    container_name: mail-nacos
    ports:
      -
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - /mail_cloud/data/nacos/logs:/home/nacos/logs
      - /mail_cloud/data/nacos/conf:/home/nacos/conf
    networks:
      - mail_cloud_net
    depends_on:
      - mail-mysql

  mail-redis:
    image: redis:latest
    container_name: mail-redis
    ports:
      -
    volumes:
      - /mail_cloud/data/redis/redis.conf:/etc/redis/redis.conf
      - /mail_cloud/data/redis/data:/data
    networks:
      - mail_cloud_net
    command: redis-server /etc/redis/redis.conf

  mail-mysql:
    image: mysql:8.0.30
    container_name: mail-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      -
    volumes:
      - /mail_cloud/data/mysql/db:/var/lib/mysql
      - /mail_cloud/data/mysql/conf/my.cnf:/etc/my.cnf
      - /mail_cloud/data/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mail_cloud_net
    command: --default-authentication-plugin=mysql_native_password

  mail-rabbitmq:
    image: rabbitmq:3-management
    container_name: mail-rabbitmq
    ports:
      -
      -
    privileged: true
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    networks:
      - mail_cloud_net
    volumes:
      - /mail_cloud/data/rabbitmq/lib:/var/lib/rabbitmq
      - /mail_cloud/data/rabbitmq/logs:/var/log/rabbitmq

networks:
  mail_cloud_net:




